apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app

