apiVersion: v1
kind: Secret
metadata:
  name: flask-app-secret
type: Opaque
data:
  # To decode base64 encoded value: echo '<base64 value>' | base64 --decode
  db_user: YWRtaW4=
  db_pass: cGFzc3dvcmQ=
